server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://203.195.238.249:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: lk123456

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml